### ISSUE TITLE
More way to handle response

### ISSUE THREAD

**Issue by hismito** [neonmoe/minreq#17]
While considering a breaking change release https://github.com/neonmoe/minreq/issues/13#issuecomment-498053281, it would nice to provide more way to handle response.

For now, `minreq` will [read all bytes into memory](https://github.com/neonmoe/minreq/blob/4f7f017246070bbfca237a247eff0936e53c0d96/src/connection.rs#L151) after receiving the response, it's convenient for response that only contains a few lines of text. When requesting a big chunk of data (for example, download a file),  there may be some trouble.

How about the `Response` struct holds the [`stream`](https://github.com/neonmoe/minreq/blob/4f7f017246070bbfca237a247eff0936e53c0d96/src/connection.rs#L151) as a field, since the http status line and headers appear before the body, we can still provide them in `Response` as pub fields. Then using dedicated methods to actually decode the body only when needed. 
```rust
struct Response<S> {
    // status fields ...
    stream: S,
}

impl<S> Response<S> {
    fn into_string(self) -> Result<String> {}

    fn into_vec(self) -> Result<Vec<u8>> {}

    fn into_stream(self) -> S {}
}
```

**Comment by neonmoe** [comment]
This is definitely a good idea, I'll have a think about how to go about implementing this in a clean manner. Also, now that the stream is passed around more, I think there's reason to consider switching to a proper type for the stream instead of a generic: it's defined in the crate (so it doesn't give users flexibility), and generics are bad for compile times.

**Comment by neonmoe** [comment]
Sorry for the delay, been very busy lately. I've started working on this now.

**Comment by neonmoe** [comment]
I experimented a bit, and ended up with the following API:
- Responses work pretty similarly to how they used to, except the body is exposed through `as_str()`, `as_bytes()` and `into_bytes()` instead of a mutable vec. It wouldn't make sense semantically to be able to modify the underlying byte array, and hiding it (ie. making it immutable) allows for optimizing `as_str`.
- The iterator is provided via `ResponseLazy` (returned by eg. `get(...).send_lazy()`), which implements `Iterator` with `Item = Result<(u8, usize), minreq::Error>`, where the `u8` is the data byte, and `usize` is the current expected amount of incoming bytes.

As for 2.0 overall, I'd like any comments on the [2.0 issue](https://github.com/neonmoe/minreq/issues/18) :)
