### ISSUE TITLE
IO error cause is shown twice with Anyhow

### ISSUE THREAD

**Issue by ollpu** [neonmoe/minreq#60]
`minreq::Error::IoError` (and possibly others) have both a `Display` impl that prints the error message, and return the contained error as a `source`, so this happens:

```rust
use anyhow::{Context, Result};
fn main() -> Result<()> {
    minreq::get("http://127.0.0.1:1234").send().context("[context]")?;
    Ok(())
}
```

```
Error: [context]

Caused by:
    0: Connection refused (os error 111)
    1: Connection refused (os error 111)
```

Not quite sure what should be done here instead.

**Comment by neonmoe** [comment]
I don't think there's an easy way to "solve" this, as the current minreq IoError doesn't have any context as to where the error originated.

Ideally there should be more granular errors that wrap the `io::Error`, so that the high-level `Display` impl would print e.g. "error reading http response body" and the specific `io::Error` would be available via `Error::source`. But I didn't originally write the crate that way, so now it would be quite a refactor, and it would introduce additional complexity to `minreq::Error` (though the additional context provided by more enumerations could be useful to crate users).

I haven't used anyhow myself, so it's good to know that there is an actual use-case for `Error::source`, and knowing that, I might end up doing this refactor someday. But I'm going to close this issue (for now), as I won't be doing that any time soon.
