### ISSUE TITLE
Regression in not including port in Host header

### ISSUE THREAD

**Issue by ollpu** [neonmoe/minreq#61]
The fix for #49 has caused a regression in our use case.

For testing we use a server at a local port (`4010`). The server generates callback URLs based on the `Host` header.

The generated URLs changed from
```
http://127.0.0.1:4010/...
```
to
```
http://127.0.0.1/...
```
which no longer work correctly.

As per spec, the port should be included in the `Host` header if it is non-default (`80` for `http`, `443` for `https`). Never including the port is not quite correct and breaks the assumptions of servers (Flask/werkzeug in our case).

Workaround is to use version `=2.4.0`.

**Comment by neonmoe** [comment]
Thanks for the report, definitely overlooked this when making the fix. The Host should indeed include the port if it's not 80 or 443, but I think the best way to do it would be to include the port if the port is manually specified. So a minreq::get to https://example.org:443 would still send Host: example.org:443. I think this is the most spec-conforming way to do it, since it doesn't say anything about omitting the port if it's 80 or 443.

Will write and publish a patch tomorrow.
