### ISSUE TITLE
Enabling https-rustls is a big problem

### ISSUE THREAD

**Issue by dosgo** [neonmoe/minreq#62]
Enabling https-rustls is 600K larger than enabling rustls in reqwest, which is not a mini.

**Comment by neonmoe** [comment]
Reqwest seems to declare the rustls dependency in a very similar fashion to minreq, so I'm not sure what can be done about this. I'd guess the effect on binary size is smaller for reqwest because it probably shares some dependencies with rustls that minreq doesn't, so minreq has to include more code when including rustls.

In any case, a stripped https-enabled hello world with minreq is 1.5 MB, where reqwest is 4.5 MB, so I'm satisfied.

But if you have any ideas for reducing rustls's footprint, I'd be eager to hear and merge them.

**Comment by dosgo** [comment]
thank you very much! I'm just a newbie, I'm just curious about this problem, it may be related to the rustls version, my target device is a router, it only has 16M ROM, and the system occupies 8M. A simple https request is compiled at least 1.6M after upx compression.
