### ISSUE TITLE
Support URL encoding?

### ISSUE THREAD

**Issue by alpha-tango-kilo** [neonmoe/minreq#67]
I've just migrated [one of my projects](https://codeberg.org/alpha-tango-kilo/imdb-id) from using `reqwest` to `minreq` and nearly halved the size of my binary, and massively improved my compile times (async begone), so huge thank you for this awesome library!

One thing that tripped me up while I was making the migration across though was needing to encode URLs/parameters. Obviously `reqwest` 'just works' in this regard, and so not being a web dev by trade, it took me a bit of poking to get to the bottom of the angry responses I was getting. (I'm not sure if it was supposed to, but enabling the `punycode` feature didn't rectify the issue)

What I was wondering was if there was a case for using a library like [`urlencoding`](https://lib.rs/crates/urlencoding) (<250 SLoC; no dependencies) as a part of `minreq`? It would make this library that bit more intuitive and easy to use. I understand that `minreq` is intended to be, well, **min**imal so I wanted to propose the idea as an issue first. I could potentially write the PR for any of the below ideas

Suggestions:
* `urlencoding` as default dependency and always use it
* `urlencoding` as an optional feature (always used when enabled)
* Document that URL encoding is the responsibility of the user

**Comment by neonmoe** [comment]
Thanks, glad it's helped! The `punycode` feature is for encoding the domain, while urlencoding is for the path and body, so it wouldn't have helped in this case, as you saw. My first instinct is to let the user handle the encoding, but since there's already precedent for these kinds of convenience features (punycode and json), I'd say the second suggestion would fit this crate the best. Of course, in either case, whether urlencoding is being done automatically or not should be documented more clearly, sorry about that.

The PR would be very welcome! :)

**Comment by neonmoe** [comment]
Actually, I think the body is only url-encoded for forms with the application/x-www-form-urlencoded Content-Type, so the feature should probably simply encode the urls, nothing else.

**Comment by alpha-tango-kilo** [comment]
Okay, so I've had a poke around the source code and I've identified some limitiations in going for suggestion 2.

It's easy to encode keys & values on `Request::with_param`, however it's going to be a right sod to also support URL encoding on `Request::new`. It'll require a couple new parser states for `parse_url` and arguably could even do with being more context aware than the current character-by-character approach due to sections like `?bool-eval=false&&true&this-a-stupid-example=i-know`, where it's not possible to interpret which ampersand splits parameters. 

Three options arise from this:
1. Reject URLs that have parameters on `Request::new` to force the usage of `Request::with_params`
    - Simplifies instead of complicating the parser
    - Provides an inconsistent experience depending on enabled features
2. Completely ditch this feature request and revert to the third suggestion above
    - Just encoding on `Request::with_param` means the library no longer feels 'self-consistent'
    - As easy for the user to implement as it is for the library
3. There's some standardised way to parse URLs that I don't know about which would make the parser changes viable (i.e. defined behaviour for what should happen in the above ambiguous case)

Would appreciate any further thoughts/insight!

**Comment by neonmoe** [comment]
That is certainly an unfortunate edge case. I'm not *that* concerned about an optional feature having slight inconsistencies (like with_param behaving differently to Request::new), since it's easy to provide documentation about these specifics right where the feature is introduced in the docs (in lib.rs). So if you opt in to the feature, chances are that you're also aware about the inconsistency.

---

There's surprisingly little about '&' in the HTTP rfcs, it seems. One useful source is the URI rfc's [Reserved Characters](https://datatracker.ietf.org/doc/html/rfc3986#section-2.2) section, specifically:

> URI producing applications should percent-encode data octets that correspond to characters in the reserved set unless these characters are specifically allowed by the URI scheme to represent data in that component.  If a reserved character is found in a URI component and no delimiting role is known for that character, then it must be interpreted as representing the data octet corresponding to that character's encoding in US-ASCII.

Based on this, when it's ambiguous, I'd parse all instances of '&' as a delimiter, so && would stay &&. Of course, you might want to actually include '&' in the value of a query parameter, but in that case, I think it's fair to leave the job of percent-encoding it to the crate user, since it's ambiguous and a reserved character.

In the case of `with_param`, I think everything should be encoded, since you're providing specifically a key and a value, not just any string of characters to append onto the url, so not percent-encoding the delimiters would actually cause unexpected behaviour.

**Comment by alpha-tango-kilo** [comment]
> I'd parse all instances of '&' as a delimiter

Thanks for making the decision for me 😅 Sounds like we'll go with 3.

> In the case of `with_param`, I think everything should be encoded, since you're providing specifically a key and a value, not just any string of characters to append onto the url, so not percent-encoding the delimiters would actually cause unexpected behaviour.

Yep, fully agree and that's what I've done in my implementation

I'll have a crack at updating the parser tomorrow and see if I can get a PR across 🚀
